### ISSUE TITLE
cubemaps-001 example missing data folder

### ISSUE THREAD

**Issue by alexdmiller** [openrndr/openrndr-tutorials#3]
I get the following error when I run it:

```
Exception in thread "main" java.io.FileNotFoundException: data/garage.dds (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:113)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at java.base/java.net.URL.openStream(URL.java:1117)
	at org.openrndr.internal.gl3.CubemapGL3$Companion.fromUrl(CubemapGL3.kt:45)
	at org.openrndr.internal.gl3.DriverGL3.createCubemapFromUrls(GLFWDriver.kt:127)
	at org.openrndr.draw.Cubemap$Companion.fromUrl(Cubemap.kt:22)
	at Example.setup(Example.kt:13)
	at org.openrndr.internal.gl3.ApplicationGL3.loop(ApplicationGL3.kt:426)
	at org.openrndr.Application$Companion.run(Application.kt:13)
	at org.openrndr.ApplicationKt.application(Application.kt:39)
	at ExampleKt.main(Example.kt:120)
```

**Comment by edwinRNDR** [comment]
@alexdmiller Thank you! I have moved the assets for `cubemaps-001` and `cubemaps-002` to the shared data folder. You may have to configure the working directory to be set to the project root for the examples to be able to find this data folder.
